DROP VIEW IF EXISTS v_submissions CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS teams CASCADE;

CREATE TABLE teams (
    team_id   SERIAL PRIMARY KEY,
    team_name TEXT NOT NULL
);

CREATE TABLE users (
    user_id    SERIAL PRIMARY KEY,
    name       TEXT NOT NULL,
    email      TEXT,
    team_id    INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,

    FOREIGN KEY (team_id) REFERENCES teams (team_id)
);

CREATE TABLE assignments (
    assignment_id SERIAL PRIMARY KEY,
    questions     JSONB
);

CREATE TABLE submissions (
    submission_id SERIAL PRIMARY KEY,
    assignment_id INT,
    answers       JSONB,
    team_id       INT,
    submitted     BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (assignment_id) REFERENCES assignments (assignment_id),
    FOREIGN KEY (team_id)       REFERENCES teams       (team_id)
);

INSERT INTO teams
    (team_name)
VALUES
    ('SplashBros')
    ,('JooJarOnThatBeat')
    ,('Grab n'' Go')
    ,('VIGINTI')
    ,('Hyper Beam')
    ,('Chemical X')
    ,('Minerva')
    ,('InstaSmart')
    ,('HelloWorld!<>')
    ,('ÖWOKE')
    ,('Anonymous')
    ,('Spicy Carbonara')
    ,('B612')
    ,('Switch2Switch')
    ,('Black-Gold')
    ,('Made in NUS')
    ,('NUSTown')
    ,('Autocropper')
    ,('Pixels Fly')
    ,('NUSJio')
    ,('Homital')
    ,('trippyy')
    ,('VisuaRL')
    ,('localink')
    ,('WonderWorld')
    ,('Cycled')
    ,('JustFind')
    ,('foo(j)foo(k)')
    ,('teamBogo')
    ,('Enoikio')
    ,('Groupfinda')
    ,('malaRamen')
    ,('Newbs')
    ,('AcademicSOS')
    ,('WeBook')
    ,('Pokka Ice Lemon Tea')
    ,('2 Legit 2 Quit')
    ,('Swappee')
    ,('''Til Kingdom Come')
    ,('Furni by TanHaus')
    ,('averageGuys')
    ,('Barter')
    ,('Hitchcock')
    ,('Idle Trading Hero')
    ,('ChioChio')
    ,('Dimensional Hackers')
    ,('Siao O(n)')
    ,('NUSocial')
    ,('DoWhat?')
    ,('Team Milankovitch')
    ,('7 Deadly Sins')
    ,('TulGan')
    ,('ElderConnect')
    ,('BridgeBot')
    ,('Team Cook')
    ,('TechXpertz')
    ,('Intense help for mugging')
    ,('Orient')
    ,('NUS Modstation')
    ,('Dev++')
    ,('GameBois')
    ,('SNUS')
    ,('SHteady')
    ,('Bloodwork')
    ,('TelMe!')
    ,('TheFreeMarket')
    ,('Valence')
    ,('AA Battery')
    ,('void TheSyntax{Error}')
    ,('SoCUnite')
    ,('Elsewhere')
    ,('Rank-a-thon')
    ,('Space Defenders')
    ,('Captain Lambda')
    ,('Stack Underflow')
    ,('Natalino BUSA')
    ,('ModuleFuture')
    ,('The Last Stand')
    ,('IndoMie')
    ,('ClassroomCompanion')
    ,('PlanNUS')
    ,('SendIt')
;

INSERT INTO users
    (team_id, name, email)
VALUES
    (01, 'Lyle Stanley', 'lyle_stanley@email.com')
    ,(01, 'Conner Millington', 'conner_millington@email.com')
    ,(02, 'Filip Santos', 'filip_santos@email.com')
    ,(02, 'Tyler Bloggs', 'tyler_bloggs@email.com')
    ,(03, 'Marisa Emery', 'marisa_emery@email.com')
    ,(03, 'Cristian Henson', 'cristian_henson@email.com')
    ,(04, 'Farzana Maguire', 'farzana_maguire@email.com')
    ,(04, 'Maryam Perkins', 'maryam_perkins@email.com')
    ,(05, 'Momina Hogan', 'momina_hogan@email.com')
    ,(05, 'Selina Ruiz', 'selina_ruiz@email.com')
    ,(06, 'Celia Lyon', 'celia_lyon@email.com')
    ,(06, 'Zayna Dodd', 'zayna_dodd@email.com')
    ,(07, 'Frederick Santiago', 'frederick_santiago@email.com')
    ,(07, 'Nelly Allen', 'nelly_allen@email.com')
    ,(08, 'Tazmin Ratliff', 'tazmin_ratliff@email.com')
    ,(08, 'Sidra Patton', 'sidra_patton@email.com')
    ,(09, 'Shakira Park', 'shakira_park@email.com')
    ,(09, 'Alfred Mcneil', 'alfred_mcneil@email.com')
    ,(10, 'Maeve Flynn', 'maeve_flynn@email.com')
    -- ,(10, 'Kaylie Stone', 'kaylie_stone@email.com')
    ,(11, 'Morwenna Dixon', 'morwenna_dixon@email.com')
    -- ,(11, 'Rhiann Hunter', 'rhiann_hunter@email.com')
    ,(12, 'Stefano Buck', 'stefano_buck@email.com')
    -- ,(12, 'Teddy Hayden', 'teddy_hayden@email.com')
    ,(13, 'Gethin Howells', 'gethin_howells@email.com')
    -- ,(13, 'Lisa-Marie Mccormack', 'lisa-marie_mccormack@email.com')
    ,(14, 'Manal Hamilton', 'manal_hamilton@email.com')
    -- ,(14, 'Misbah Drake', 'misbah_drake@email.com')
    ,(15, 'Ubaid Frye', 'ubaid_frye@email.com')
    -- ,(15, 'Dan Connelly', 'dan_connelly@email.com')
    ,(16, 'Francesca Tucker', 'francesca_tucker@email.com')
    -- ,(16, 'Izaac Jeffery', 'izaac_jeffery@email.com')
    ,(17, 'Teagan Gamble', 'teagan_gamble@email.com')
    -- ,(17, 'Lee Moon', 'lee_moon@email.com')
    ,(18, 'Olli Lam', 'olli_lam@email.com')
    -- ,(18, 'Lily Ray', 'lily_ray@email.com')
    ,(19, 'Lorenzo Escobar', 'lorenzo_escobar@email.com')
    -- ,(19, 'Jasmin Pope', 'jasmin_pope@email.com')
    ,(20, 'Heath Espinoza', 'heath_espinoza@email.com')
    -- ,(20, 'Arvin Kennedy', 'arvin_kennedy@email.com')
    ,(21, 'Mohammed Nolan', 'mohammed_nolan@email.com')
    -- ,(21, 'Ayyub Cortez', 'ayyub_cortez@email.com')
    ,(22, 'Katelyn Coffey', 'katelyn_coffey@email.com')
    -- ,(22, 'Krystian Boyce', 'krystian_boyce@email.com')
    ,(23, 'Ivy-Rose Mcdermott', 'ivy-rose_mcdermott@email.com')
    -- ,(23, 'Zack Bell', 'zack_bell@email.com')
    ,(24, 'Noa Horner', 'noa_horner@email.com')
    -- ,(24, 'Lincoln Stevens', 'lincoln_stevens@email.com')
    ,(25, 'Lillian Mclaughlin', 'lillian_mclaughlin@email.com')
    -- ,(25, 'Beck Coleman', 'beck_coleman@email.com')
    ,(26, 'Haydn Donaldson', 'haydn_donaldson@email.com')
    -- ,(26, 'Sam Bevan', 'sam_bevan@email.com')
    ,(27, 'Bogdan Fields', 'bogdan_fields@email.com')
    -- ,(27, 'Danielle Gilmore', 'danielle_gilmore@email.com')
    ,(28, 'Fearne Howarth', 'fearne_howarth@email.com')
    -- ,(28, 'Salman Feeney', 'salman_feeney@email.com')
    ,(29, 'Taylor Burn', 'taylor_burn@email.com')
    ,(29, 'Leigh Serrano', 'leigh_serrano@email.com')
    ,(30, 'Suhail Frey', 'suhail_frey@email.com')
    ,(30, 'Ciaron Palmer', 'ciaron_palmer@email.com')
    ,(31, 'Lacey Mckenzie', 'lacey_mckenzie@email.com')
    ,(31, 'Priscilla Estrada', 'priscilla_estrada@email.com')
    ,(32, 'Omari Hogg', 'omari_hogg@email.com')
    ,(32, 'Eshal Houston', 'eshal_houston@email.com')
    ,(33, 'Cassandra Perry', 'cassandra_perry@email.com')
    ,(33, 'Macauley Bull', 'macauley_bull@email.com')
    ,(34, 'Lorelai Hahn', 'lorelai_hahn@email.com')
    ,(34, 'Ayva Warren', 'ayva_warren@email.com')
    ,(35, 'Ned Whitfield', 'ned_whitfield@email.com')
    ,(35, 'Taha Hood', 'taha_hood@email.com')
    ,(36, 'Gregg Melendez', 'gregg_melendez@email.com')
    ,(36, 'Maizie Schmitt', 'maizie_schmitt@email.com')
    ,(37, 'Linda Hyde', 'linda_hyde@email.com')
    ,(37, 'Daniaal Ashton', 'daniaal_ashton@email.com')
    ,(38, 'Gabriela Peters', 'gabriela_peters@email.com')
    ,(38, 'Sylvie Ingram', 'sylvie_ingram@email.com')
    ,(39, 'Jay-Jay Boone', 'jay-jay_boone@email.com')
    ,(39, 'Mariyah Rowe', 'mariyah_rowe@email.com')
    ,(40, 'Lyndon Austin', 'lyndon_austin@email.com')
    ,(40, 'Saim Lopez', 'saim_lopez@email.com')
    ,(41, 'Kayla Callahan', 'kayla_callahan@email.com')
    ,(41, 'Kathryn Villegas', 'kathryn_villegas@email.com')
    ,(42, 'Brodie Coates', 'brodie_coates@email.com')
    ,(42, 'Roseanna Adamson', 'roseanna_adamson@email.com')
    ,(43, 'Jess Corrigan', 'jess_corrigan@email.com')
    ,(43, 'Brittney Castillo', 'brittney_castillo@email.com')
    ,(44, 'Cieran Kearney', 'cieran_kearney@email.com')
    ,(44, 'Aysha Mccray', 'aysha_mccray@email.com')
    ,(45, 'Faris Riley', 'faris_riley@email.com')
    ,(45, 'Marta Major', 'marta_major@email.com')
    ,(46, 'Tre Bowler', 'tre_bowler@email.com')
    ,(46, 'Billie-Jo Townsend', 'billie-jo_townsend@email.com')
    ,(47, 'Nur O''Connor', 'connor')
    ,(47, 'Ariana Wilson', 'ariana_wilson@email.com')
    ,(48, 'Chanice Hanna', 'chanice_hanna@email.com')
    ,(48, 'Kristen Bate', 'kristen_bate@email.com')
    ,(49, 'Ronnie Kirby', 'ronnie_kirby@email.com')
    ,(49, 'Kadeem Oneill', 'kadeem_oneill@email.com')
    ,(50, 'Denzel Hough', 'denzel_hough@email.com')
    ,(50, 'Shana Williamson', 'shana_williamson@email.com')
    ,(51, 'Sophie-Louise Howe', 'sophie-louise_howe@email.com')
    ,(51, 'Julien Obrien', 'julien_obrien@email.com')
    ,(52, 'Gabrielle Quintana', 'gabrielle_quintana@email.com')
    ,(52, 'Kylo Churchill', 'kylo_churchill@email.com')
    ,(53, 'Fearne Wynn', 'fearne_wynn@email.com')
    ,(53, 'Edgar Dalby', 'edgar_dalby@email.com')
    ,(54, 'Roma Wiggins', 'roma_wiggins@email.com')
    ,(54, 'Tamsin Hays', 'tamsin_hays@email.com')
    ,(55, 'Alayna Powell', 'alayna_powell@email.com')
    ,(55, 'Keavy Sampson', 'keavy_sampson@email.com')
    ,(56, 'Angelo Macgregor', 'angelo_macgregor@email.com')
    ,(56, 'Aminah Leigh', 'aminah_leigh@email.com')
    ,(57, 'Nana Bains', 'nana_bains@email.com')
    ,(57, 'Jesus Donald', 'jesus_donald@email.com')
    ,(58, 'Susannah White', 'susannah_white@email.com')
    ,(58, 'Ciaran Camacho', 'ciaran_camacho@email.com')
    ,(59, 'Jackson Redmond', 'jackson_redmond@email.com')
    ,(59, 'Eduard Mohamed', 'eduard_mohamed@email.com')
    ,(60, 'Jermaine Vang', 'jermaine_vang@email.com')
    ,(60, 'Layan Blundell', 'layan_blundell@email.com')
    ,(61, 'Kamron Barrow', 'kamron_barrow@email.com')
    ,(61, 'Walid Petty', 'walid_petty@email.com')
    ,(62, 'Cherish Mullins', 'cherish_mullins@email.com')
    ,(62, 'Andrei Khan', 'andrei_khan@email.com')
    ,(63, 'Niko Truong', 'niko_truong@email.com')
    ,(63, 'Kady Mccoy', 'kady_mccoy@email.com')
    ,(64, 'Donte Maguire', 'donte_maguire@email.com')
    ,(64, 'Cathal Escobar', 'cathal_escobar@email.com')
    ,(65, 'Hebe Hester', 'hebe_hester@email.com')
    ,(65, 'Samantha Mahoney', 'samantha_mahoney@email.com')
    -- ,(66, 'Alexandra Stephenson', 'alexandra_stephenson@email.com')
    -- ,(66, 'Jayda Roy', 'jayda_roy@email.com')
    -- ,(67, 'Jamie Chandler', 'jamie_chandler@email.com')
    -- ,(67, 'Gertrude Bartlett', 'gertrude_bartlett@email.com')
    -- ,(68, 'Florence Adams', 'florence_adams@email.com')
    -- ,(68, 'Vanessa Ross', 'vanessa_ross@email.com')
    -- ,(69, 'Jimi Parsons', 'jimi_parsons@email.com')
    -- ,(69, 'Hashir Alexander', 'hashir_alexander@email.com')
    -- ,(70, 'Jason Russo', 'jason_russo@email.com')
    -- ,(70, 'Olaf Espinosa', 'olaf_espinosa@email.com')
    ,(71, 'Anita Hendricks', 'anita_hendricks@email.com')
    ,(71, 'Laurie Mcneill', 'laurie_mcneill@email.com')
    ,(72, 'Kirby Sumner', 'kirby_sumner@email.com')
    ,(72, 'Abel Hodges', 'abel_hodges@email.com')
    ,(73, 'Kie Mcdougall', 'kie_mcdougall@email.com')
    ,(73, 'Wayne Vincent', 'wayne_vincent@email.com')
    ,(74, 'Joy Esparza', 'joy_esparza@email.com')
    ,(74, 'Sallie Blake', 'sallie_blake@email.com')
    ,(75, 'Zackary Mckinney', 'zackary_mckinney@email.com')
    ,(75, 'Toby Franklin', 'toby_franklin@email.com')
    ,(76, 'Talha Hatfield', 'talha_hatfield@email.com')
    ,(76, 'Dominika Long', 'dominika_long@email.com')
    ,(77, 'Tayla Witt', 'tayla_witt@email.com')
    ,(77, 'Ritchie Hodson', 'ritchie_hodson@email.com')
    ,(78, 'Lloyd Metcalfe', 'lloyd_metcalfe@email.com')
    ,(78, 'Georgia Ellison', 'georgia_ellison@email.com')
    ,(79, 'Scott Tran', 'scott_tran@email.com')
    ,(79, 'Avni Bowes', 'avni_bowes@email.com')
    ,(80, 'Juanita Jenkins', 'juanita_jenkins@email.com')
    ,(80, 'Eduardo Pittman', 'eduardo_pittman@email.com')
    ,(81, 'Reem Leblanc', 'reem_leblanc@email.com')
    ,(81, 'Amiya North', 'amiya_north@email.com')
    ,(82, 'Lyndon Clarkson', 'lyndon_clarkson@email.com')
    ,(82, 'Anisa Zavala', 'anisa_zavala@email.com')
;

INSERT INTO assignments
    (questions)
VALUES
    ('[]')
    ,('[]')
    ,('[]')
    ,('[]')
;

INSERT INTO submissions
    (assignment_id, team_id, answers, submitted)
VALUES
    (1, 01, '[]', FALSE)
    ,(1, 02, '[]', FALSE)
    ,(1, 03, '[]', FALSE)
    ,(1, 04, '[]', FALSE)
    ,(1, 05, '[]', FALSE)
    ,(1, 06, '[]', FALSE)
    ,(1, 07, '[]', FALSE)
    ,(1, 08, '[]', FALSE)
    ,(1, 09, '[]', FALSE)
    ,(1, 10, '[]', FALSE)
    ,(1, 11, '[]', FALSE)
    ,(1, 12, '[]', FALSE)
    ,(1, 13, '[]', FALSE)
    ,(1, 14, '[]', FALSE)
    ,(1, 15, '[]', FALSE)
    ,(1, 16, '[]', FALSE)
    ,(1, 17, '[]', FALSE)
    ,(1, 18, '[]', FALSE)
    ,(1, 19, '[]', FALSE)
    ,(1, 20, '[]', FALSE)
    ,(1, 21, '[]', FALSE)
    ,(1, 22, '[]', FALSE)
    ,(1, 23, '[]', FALSE)
    ,(1, 24, '[]', FALSE)
    ,(1, 25, '[]', FALSE)
    ,(1, 26, '[]', FALSE)
    ,(1, 27, '[]', FALSE)
    ,(1, 28, '[]', FALSE)
    ,(1, 29, '[]', FALSE)
    ,(1, 30, '[]', FALSE)
    ,(1, 31, '[]', FALSE)
    ,(1, 32, '[]', FALSE)
    ,(1, 33, '[]', FALSE)
    ,(1, 34, '[]', FALSE)
    ,(1, 35, '[]', FALSE)
    ,(1, 36, '[]', FALSE)
    ,(1, 37, '[]', FALSE)
    ,(1, 38, '[]', FALSE)
    ,(1, 39, '[]', FALSE)
    ,(1, 40, '[]', FALSE)
    ,(1, 41, '[]', FALSE)
    ,(1, 42, '[]', FALSE)
    ,(1, 43, '[]', FALSE)
    ,(1, 44, '[]', FALSE)
    ,(1, 45, '[]', FALSE)
    ,(1, 46, '[]', FALSE)
    ,(1, 47, '[]', FALSE)
    ,(1, 48, '[]', FALSE)
    ,(1, 49, '[]', FALSE)
    ,(1, 50, '[]', FALSE)
    ,(1, 51, '[]', FALSE)
    ,(1, 52, '[]', FALSE)
    ,(1, 53, '[]', FALSE)
    ,(1, 54, '[]', FALSE)
    ,(1, 55, '[]', FALSE)
    ,(1, 56, '[]', FALSE)
    ,(1, 57, '[]', FALSE)
    ,(1, 58, '[]', FALSE)
    ,(1, 59, '[]', FALSE)
    ,(1, 60, '[]', FALSE)
    ,(1, 61, '[]', FALSE)
    ,(1, 62, '[]', FALSE)
    ,(1, 63, '[]', FALSE)
    ,(1, 64, '[]', FALSE)
    ,(1, 65, '[]', FALSE)
    ,(1, 66, '[]', FALSE)
    ,(1, 67, '[]', FALSE)
    ,(1, 68, '[]', FALSE)
    ,(1, 69, '[]', FALSE)
    ,(1, 70, '[]', FALSE)
    ,(1, 71, '[]', FALSE)
    ,(1, 72, '[]', FALSE)
    ,(1, 73, '[]', FALSE)
    ,(1, 74, '[]', FALSE)
    ,(1, 75, '[]', FALSE)
    ,(1, 76, '[]', FALSE)
    ,(1, 77, '[]', FALSE)
    ,(1, 78, '[]', FALSE)
    ,(1, 79, '[]', FALSE)
    ,(1, 80, '[]', FALSE)
    ,(1, 81, '[]', FALSE)
    ,(1, 82, '[]', FALSE)
    ,(2, 01, '[]', FALSE)
    ,(2, 02, '[]', FALSE)
    ,(2, 03, '[]', FALSE)
    ,(2, 04, '[]', FALSE)
    ,(2, 05, '[]', FALSE)
    ,(2, 06, '[]', FALSE)
    ,(2, 07, '[]', FALSE)
    ,(2, 08, '[]', FALSE)
    ,(2, 09, '[]', FALSE)
    ,(2, 10, '[]', FALSE)
    ,(2, 11, '[]', FALSE)
    ,(2, 12, '[]', FALSE)
    ,(2, 13, '[]', FALSE)
    ,(2, 14, '[]', FALSE)
    ,(2, 15, '[]', FALSE)
    ,(2, 16, '[]', FALSE)
    ,(2, 17, '[]', FALSE)
    ,(2, 18, '[]', FALSE)
    ,(2, 19, '[]', FALSE)
    ,(2, 20, '[]', FALSE)
    ,(2, 21, '[]', FALSE)
    ,(2, 22, '[]', FALSE)
    ,(2, 23, '[]', FALSE)
    ,(2, 24, '[]', FALSE)
    ,(2, 25, '[]', FALSE)
    ,(2, 26, '[]', FALSE)
    ,(2, 27, '[]', FALSE)
    ,(2, 28, '[]', FALSE)
    ,(2, 29, '[]', FALSE)
    ,(2, 30, '[]', FALSE)
    ,(2, 31, '[]', FALSE)
    ,(2, 32, '[]', FALSE)
    ,(2, 33, '[]', FALSE)
    ,(2, 34, '[]', FALSE)
    ,(2, 35, '[]', FALSE)
    ,(2, 36, '[]', FALSE)
    ,(2, 37, '[]', FALSE)
    ,(2, 38, '[]', FALSE)
    ,(2, 39, '[]', FALSE)
    ,(2, 40, '[]', FALSE)
    ,(2, 41, '[]', FALSE)
    ,(2, 42, '[]', FALSE)
    ,(2, 43, '[]', FALSE)
    ,(2, 44, '[]', FALSE)
    ,(2, 45, '[]', FALSE)
    ,(2, 46, '[]', FALSE)
    ,(2, 47, '[]', FALSE)
    ,(2, 48, '[]', FALSE)
    ,(2, 49, '[]', FALSE)
    ,(2, 50, '[]', FALSE)
    ,(2, 51, '[]', FALSE)
    ,(2, 52, '[]', FALSE)
    ,(2, 53, '[]', FALSE)
    ,(2, 54, '[]', FALSE)
    ,(2, 55, '[]', FALSE)
    ,(2, 56, '[]', FALSE)
    ,(2, 57, '[]', FALSE)
    ,(2, 58, '[]', FALSE)
    ,(2, 59, '[]', FALSE)
    ,(2, 60, '[]', FALSE)
    ,(2, 61, '[]', FALSE)
    ,(2, 62, '[]', FALSE)
    ,(2, 63, '[]', FALSE)
    ,(2, 64, '[]', FALSE)
    ,(2, 65, '[]', FALSE)
    ,(2, 66, '[]', FALSE)
    ,(2, 67, '[]', FALSE)
    ,(2, 68, '[]', FALSE)
    ,(2, 69, '[]', FALSE)
    ,(2, 70, '[]', FALSE)
    ,(2, 71, '[]', FALSE)
    ,(2, 72, '[]', FALSE)
    ,(2, 73, '[]', FALSE)
    ,(2, 74, '[]', FALSE)
    ,(2, 75, '[]', FALSE)
    ,(2, 76, '[]', FALSE)
    ,(2, 77, '[]', FALSE)
    ,(2, 78, '[]', FALSE)
    ,(2, 79, '[]', FALSE)
    ,(2, 80, '[]', FALSE)
    ,(2, 81, '[]', FALSE)
    ,(2, 82, '[]', FALSE)
    ,(3, 01, '[]', FALSE)
    ,(3, 02, '[]', FALSE)
    ,(3, 03, '[]', FALSE)
    ,(3, 04, '[]', FALSE)
    ,(3, 05, '[]', FALSE)
    ,(3, 06, '[]', FALSE)
    ,(3, 07, '[]', FALSE)
    ,(3, 08, '[]', FALSE)
    ,(3, 09, '[]', FALSE)
    ,(3, 10, '[]', FALSE)
    ,(3, 11, '[]', FALSE)
    ,(3, 12, '[]', FALSE)
    ,(3, 13, '[]', FALSE)
    ,(3, 14, '[]', FALSE)
    ,(3, 15, '[]', FALSE)
    ,(3, 16, '[]', FALSE)
    ,(3, 17, '[]', FALSE)
    ,(3, 18, '[]', FALSE)
    ,(3, 19, '[]', FALSE)
    ,(3, 20, '[]', FALSE)
    ,(3, 21, '[]', FALSE)
    ,(3, 22, '[]', FALSE)
    ,(3, 23, '[]', FALSE)
    ,(3, 24, '[]', FALSE)
    ,(3, 25, '[]', FALSE)
    ,(3, 26, '[]', FALSE)
    ,(3, 27, '[]', FALSE)
    ,(3, 28, '[]', FALSE)
    ,(3, 29, '[]', FALSE)
    ,(3, 30, '[]', FALSE)
    ,(3, 31, '[]', FALSE)
    ,(3, 32, '[]', FALSE)
    ,(3, 33, '[]', FALSE)
    ,(3, 34, '[]', FALSE)
    ,(3, 35, '[]', FALSE)
    ,(3, 36, '[]', FALSE)
    ,(3, 37, '[]', FALSE)
    ,(3, 38, '[]', FALSE)
    ,(3, 39, '[]', FALSE)
    ,(3, 40, '[]', FALSE)
    ,(3, 41, '[]', FALSE)
    ,(3, 42, '[]', FALSE)
    ,(3, 43, '[]', FALSE)
    ,(3, 44, '[]', FALSE)
    ,(3, 45, '[]', FALSE)
    ,(3, 46, '[]', FALSE)
    ,(3, 47, '[]', FALSE)
    ,(3, 48, '[]', FALSE)
    ,(3, 49, '[]', FALSE)
    ,(3, 50, '[]', FALSE)
    ,(3, 51, '[]', FALSE)
    ,(3, 52, '[]', FALSE)
    ,(3, 53, '[]', FALSE)
    ,(3, 54, '[]', FALSE)
    ,(3, 55, '[]', FALSE)
    ,(3, 56, '[]', FALSE)
    ,(3, 57, '[]', FALSE)
    ,(3, 58, '[]', FALSE)
    ,(3, 59, '[]', FALSE)
    ,(3, 60, '[]', FALSE)
    ,(3, 61, '[]', FALSE)
    ,(3, 62, '[]', FALSE)
    ,(3, 63, '[]', FALSE)
    ,(3, 64, '[]', FALSE)
    ,(3, 65, '[]', FALSE)
    ,(3, 66, '[]', FALSE)
    ,(3, 67, '[]', FALSE)
    ,(3, 68, '[]', FALSE)
    ,(3, 69, '[]', FALSE)
    ,(3, 70, '[]', FALSE)
    ,(3, 71, '[]', FALSE)
    ,(3, 72, '[]', FALSE)
    ,(3, 73, '[]', FALSE)
    ,(3, 74, '[]', FALSE)
    ,(3, 75, '[]', FALSE)
    ,(3, 76, '[]', FALSE)
    ,(3, 77, '[]', FALSE)
    ,(3, 78, '[]', FALSE)
    ,(3, 79, '[]', FALSE)
    ,(3, 80, '[]', FALSE)
    ,(3, 81, '[]', FALSE)
    ,(3, 82, '[]', FALSE)
    ,(4, 01, '[]', FALSE)
    ,(4, 02, '[]', FALSE)
    ,(4, 03, '[]', FALSE)
    ,(4, 04, '[]', FALSE)
    ,(4, 05, '[]', FALSE)
    ,(4, 06, '[]', FALSE)
    ,(4, 07, '[]', FALSE)
    ,(4, 08, '[]', FALSE)
    ,(4, 09, '[]', FALSE)
    ,(4, 10, '[]', FALSE)
    ,(4, 11, '[]', FALSE)
    ,(4, 12, '[]', FALSE)
    ,(4, 13, '[]', FALSE)
    ,(4, 14, '[]', FALSE)
    ,(4, 15, '[]', FALSE)
    ,(4, 16, '[]', FALSE)
    ,(4, 17, '[]', FALSE)
    ,(4, 18, '[]', FALSE)
    ,(4, 19, '[]', FALSE)
    ,(4, 20, '[]', FALSE)
    ,(4, 21, '[]', FALSE)
    ,(4, 22, '[]', FALSE)
    ,(4, 23, '[]', FALSE)
    ,(4, 24, '[]', FALSE)
    ,(4, 25, '[]', FALSE)
    ,(4, 26, '[]', FALSE)
    ,(4, 27, '[]', FALSE)
    ,(4, 28, '[]', FALSE)
    ,(4, 29, '[]', FALSE)
    ,(4, 30, '[]', FALSE)
    ,(4, 31, '[]', FALSE)
    ,(4, 32, '[]', FALSE)
    ,(4, 33, '[]', FALSE)
    ,(4, 34, '[]', FALSE)
    ,(4, 35, '[]', FALSE)
    ,(4, 36, '[]', FALSE)
    ,(4, 37, '[]', FALSE)
    ,(4, 38, '[]', FALSE)
    ,(4, 39, '[]', FALSE)
    ,(4, 40, '[]', FALSE)
    ,(4, 41, '[]', FALSE)
    ,(4, 42, '[]', FALSE)
    ,(4, 43, '[]', FALSE)
    ,(4, 44, '[]', FALSE)
    ,(4, 45, '[]', FALSE)
    ,(4, 46, '[]', FALSE)
    ,(4, 47, '[]', FALSE)
    ,(4, 48, '[]', FALSE)
    ,(4, 49, '[]', FALSE)
    ,(4, 50, '[]', FALSE)
    ,(4, 51, '[]', FALSE)
    ,(4, 52, '[]', FALSE)
    ,(4, 53, '[]', FALSE)
    ,(4, 54, '[]', FALSE)
    ,(4, 55, '[]', FALSE)
    ,(4, 56, '[]', FALSE)
    ,(4, 57, '[]', FALSE)
    ,(4, 58, '[]', FALSE)
    ,(4, 59, '[]', FALSE)
    ,(4, 60, '[]', FALSE)
    ,(4, 61, '[]', FALSE)
    ,(4, 62, '[]', FALSE)
    ,(4, 63, '[]', FALSE)
    ,(4, 64, '[]', FALSE)
    ,(4, 65, '[]', FALSE)
    ,(4, 66, '[]', FALSE)
    ,(4, 67, '[]', FALSE)
    ,(4, 68, '[]', FALSE)
    ,(4, 69, '[]', FALSE)
    ,(4, 70, '[]', FALSE)
    ,(4, 71, '[]', FALSE)
    ,(4, 72, '[]', FALSE)
    ,(4, 73, '[]', FALSE)
    ,(4, 74, '[]', FALSE)
    ,(4, 75, '[]', FALSE)
    ,(4, 76, '[]', FALSE)
    ,(4, 77, '[]', FALSE)
    ,(4, 78, '[]', FALSE)
    ,(4, 79, '[]', FALSE)
    ,(4, 80, '[]', FALSE)
    ,(4, 81, '[]', FALSE)
    ,(4, 82, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
    ,(4, NULL, '[]', FALSE)
;

